`timescale 1ns/1ps
// Auto-generated by tools/make_fastv2_network_stage.py. Do not hand edit.
module fastv2_network_desc_rom(
    input  wire [7:0]  i_layer,
    output reg  [3:0]  o_layer_type,
    output reg  [3:0]  o_fast_hint,
    output reg  [15:0] o_in_w, o_in_h, o_in_c,
    output reg  [15:0] o_out_w, o_out_h, o_out_c,
    output reg  [3:0]  o_kernel, o_stride, o_pad,
    output reg  [31:0] o_ifm_word_ofs,
    output reg  [31:0] o_ifm2_word_ofs,
    output reg  [31:0] o_ofm_word_ofs,
    output reg  [31:0] o_wgt_word_ofs,
    output reg  [31:0] o_bias_word_ofs,
    output reg  [31:0] o_scale_word_ofs
);
    always @* begin
        o_layer_type=4'd0; o_fast_hint=4'd0;
        o_in_w=16'd0; o_in_h=16'd0; o_in_c=16'd0; o_out_w=16'd0; o_out_h=16'd0; o_out_c=16'd0;
        o_kernel=4'd0; o_stride=4'd0; o_pad=4'd0;
        o_ifm_word_ofs=32'd0; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd0;
        o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
        case(i_layer)
            8'd0: begin
                o_layer_type=1; o_fast_hint=1;
                o_in_w=16'd256; o_in_h=16'd256; o_in_c=16'd3;
                o_out_w=16'd256; o_out_h=16'd256; o_out_c=16'd16;
                o_kernel=3; o_stride=1; o_pad=1;
                o_ifm_word_ofs=32'd0; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd0;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd576; o_scale_word_ofs=32'd584;
            end
            8'd1: begin
                o_layer_type=2; o_fast_hint=3;
                o_in_w=16'd256; o_in_h=16'd256; o_in_c=16'd16;
                o_out_w=16'd128; o_out_h=16'd128; o_out_c=16'd16;
                o_kernel=2; o_stride=2; o_pad=0;
                o_ifm_word_ofs=32'd0; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd262144;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd2: begin
                o_layer_type=1; o_fast_hint=1;
                o_in_w=16'd128; o_in_h=16'd128; o_in_c=16'd16;
                o_out_w=16'd128; o_out_h=16'd128; o_out_c=16'd32;
                o_kernel=3; o_stride=1; o_pad=1;
                o_ifm_word_ofs=32'd262144; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd327680;
                o_wgt_word_ofs=32'd592; o_bias_word_ofs=32'd1744; o_scale_word_ofs=32'd1760;
            end
            8'd3: begin
                o_layer_type=2; o_fast_hint=3;
                o_in_w=16'd128; o_in_h=16'd128; o_in_c=16'd32;
                o_out_w=16'd64; o_out_h=16'd64; o_out_c=16'd32;
                o_kernel=2; o_stride=2; o_pad=0;
                o_ifm_word_ofs=32'd327680; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd458752;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd4: begin
                o_layer_type=1; o_fast_hint=1;
                o_in_w=16'd64; o_in_h=16'd64; o_in_c=16'd32;
                o_out_w=16'd64; o_out_h=16'd64; o_out_c=16'd64;
                o_kernel=3; o_stride=1; o_pad=1;
                o_ifm_word_ofs=32'd458752; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd491520;
                o_wgt_word_ofs=32'd1776; o_bias_word_ofs=32'd6384; o_scale_word_ofs=32'd6416;
            end
            8'd5: begin
                o_layer_type=2; o_fast_hint=3;
                o_in_w=16'd64; o_in_h=16'd64; o_in_c=16'd64;
                o_out_w=16'd32; o_out_h=16'd32; o_out_c=16'd64;
                o_kernel=2; o_stride=2; o_pad=0;
                o_ifm_word_ofs=32'd491520; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd557056;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd6: begin
                o_layer_type=1; o_fast_hint=1;
                o_in_w=16'd32; o_in_h=16'd32; o_in_c=16'd64;
                o_out_w=16'd32; o_out_h=16'd32; o_out_c=16'd128;
                o_kernel=3; o_stride=1; o_pad=1;
                o_ifm_word_ofs=32'd557056; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd573440;
                o_wgt_word_ofs=32'd6448; o_bias_word_ofs=32'd24880; o_scale_word_ofs=32'd24944;
            end
            8'd7: begin
                o_layer_type=2; o_fast_hint=3;
                o_in_w=16'd32; o_in_h=16'd32; o_in_c=16'd128;
                o_out_w=16'd16; o_out_h=16'd16; o_out_c=16'd128;
                o_kernel=2; o_stride=2; o_pad=0;
                o_ifm_word_ofs=32'd573440; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd606208;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd8: begin
                o_layer_type=1; o_fast_hint=1;
                o_in_w=16'd16; o_in_h=16'd16; o_in_c=16'd128;
                o_out_w=16'd16; o_out_h=16'd16; o_out_c=16'd256;
                o_kernel=3; o_stride=1; o_pad=1;
                o_ifm_word_ofs=32'd606208; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd614400;
                o_wgt_word_ofs=32'd25008; o_bias_word_ofs=32'd98736; o_scale_word_ofs=32'd98864;
            end
            8'd9: begin
                o_layer_type=2; o_fast_hint=3;
                o_in_w=16'd16; o_in_h=16'd16; o_in_c=16'd256;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd256;
                o_kernel=2; o_stride=2; o_pad=0;
                o_ifm_word_ofs=32'd614400; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd630784;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd10: begin
                o_layer_type=1; o_fast_hint=1;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd256;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd512;
                o_kernel=3; o_stride=1; o_pad=1;
                o_ifm_word_ofs=32'd630784; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd634880;
                o_wgt_word_ofs=32'd98992; o_bias_word_ofs=32'd393904; o_scale_word_ofs=32'd394160;
            end
            8'd11: begin
                o_layer_type=2; o_fast_hint=3;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd512;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd512;
                o_kernel=2; o_stride=1; o_pad=0;
                o_ifm_word_ofs=32'd634880; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd643072;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd12: begin
                o_layer_type=1; o_fast_hint=2;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd512;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd256;
                o_kernel=1; o_stride=1; o_pad=0;
                o_ifm_word_ofs=32'd643072; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd651264;
                o_wgt_word_ofs=32'd394416; o_bias_word_ofs=32'd427184; o_scale_word_ofs=32'd427312;
            end
            8'd13: begin
                o_layer_type=1; o_fast_hint=1;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd256;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd512;
                o_kernel=3; o_stride=1; o_pad=1;
                o_ifm_word_ofs=32'd651264; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd655360;
                o_wgt_word_ofs=32'd427440; o_bias_word_ofs=32'd722352; o_scale_word_ofs=32'd722608;
            end
            8'd14: begin
                o_layer_type=1; o_fast_hint=2;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd512;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd195;
                o_kernel=1; o_stride=1; o_pad=0;
                o_ifm_word_ofs=32'd655360; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd663552;
                o_wgt_word_ofs=32'd722864; o_bias_word_ofs=32'd747824; o_scale_word_ofs=32'd747922;
            end
            8'd15: begin
                o_layer_type=5; o_fast_hint=7;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd195;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd195;
                o_kernel=0; o_stride=0; o_pad=0;
                o_ifm_word_ofs=32'd663552; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd663552;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd16: begin
                o_layer_type=3; o_fast_hint=4;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd195;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd256;
                o_kernel=0; o_stride=0; o_pad=0;
                o_ifm_word_ofs=32'd651264; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd666688;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd17: begin
                o_layer_type=1; o_fast_hint=2;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd256;
                o_out_w=16'd8; o_out_h=16'd8; o_out_c=16'd128;
                o_kernel=1; o_stride=1; o_pad=0;
                o_ifm_word_ofs=32'd666688; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd668736;
                o_wgt_word_ofs=32'd748020; o_bias_word_ofs=32'd756212; o_scale_word_ofs=32'd756276;
            end
            8'd18: begin
                o_layer_type=4; o_fast_hint=6;
                o_in_w=16'd8; o_in_h=16'd8; o_in_c=16'd128;
                o_out_w=16'd16; o_out_h=16'd16; o_out_c=16'd128;
                o_kernel=0; o_stride=2; o_pad=0;
                o_ifm_word_ofs=32'd668736; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd676928;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd19: begin
                o_layer_type=3; o_fast_hint=5;
                o_in_w=16'd16; o_in_h=16'd16; o_in_c=16'd128;
                o_out_w=16'd16; o_out_h=16'd16; o_out_c=16'd384;
                o_kernel=0; o_stride=0; o_pad=0;
                o_ifm_word_ofs=32'd676928; o_ifm2_word_ofs=32'd614400; o_ofm_word_ofs=32'd676928;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            8'd20: begin
                o_layer_type=1; o_fast_hint=2;
                o_in_w=16'd16; o_in_h=16'd16; o_in_c=16'd384;
                o_out_w=16'd16; o_out_h=16'd16; o_out_c=16'd195;
                o_kernel=1; o_stride=1; o_pad=0;
                o_ifm_word_ofs=32'd676928; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd701504;
                o_wgt_word_ofs=32'd756340; o_bias_word_ofs=32'd775060; o_scale_word_ofs=32'd775158;
            end
            8'd21: begin
                o_layer_type=5; o_fast_hint=7;
                o_in_w=16'd16; o_in_h=16'd16; o_in_c=16'd195;
                o_out_w=16'd16; o_out_h=16'd16; o_out_c=16'd195;
                o_kernel=0; o_stride=0; o_pad=0;
                o_ifm_word_ofs=32'd701504; o_ifm2_word_ofs=32'd0; o_ofm_word_ofs=32'd701504;
                o_wgt_word_ofs=32'd0; o_bias_word_ofs=32'd0; o_scale_word_ofs=32'd0;
            end
            default: begin end
        endcase
    end
endmodule
